language: go
go:
- 1.10.x
env:
  global:
  - secure: "X958L6Vy3Xwn4VzCzfwOPWG5bnuaeVbY2OKXTG2s/KsfeNfrl6/ZkUct5vZL8//+bwJkVVCobVG2KCmUyyeCa1EjR9ED0GH03IUEJlXs1c7v0BacNJ2D2bs8HxsjXHjuDYBh/l1zP6GhGwsZkPhFSx9ViG8M90eg6cUsPlDVppE8PfzhrNa4GwHqGieQTzke7kWiF9484YRcsTLGOgbvkmgCo9uvW/6TFjwkNd6lrjhIcDnB3YPNTP+mDyXBghwpAjTrtV2ZvkbkC4lwM3/gCMww45Y3OUcj8PT1Ez1E86tV/a7EwgyQPo2ho/koe14kyZ0JNZpq5zHaE6L+mJhCqHAITxt2fv81WsCnYnOG5zwtq5N2Re14GIq+wLClTS7/5wYwo1UhtiaBO3Cp5AjetHh8ZnYsNmqmY+7rx1w6/TsdG9i7LCX5rDGdQEOQLpDHRkTx+zEFmlEbPUrEypJ6vEulKkD2ydIzjQmJpRpXpZWA9ItIMcoAcftK5IUlWBuD2rSgHznJdeNVdEcSfiQQXbrKn13ycpK51ENFHp6V6+wJTbNZ4H2qHURDIgkwc2TBMeQ6GpkfsKvdbKZ6FEoZg08ULZathMUxnHaoXc36x4JFqcrcZZsnAxVCUbkDX82mwVIYsGVbM0H8XtHeXrvGCmED1/su3WHfN4S8mWuetTI="
os:
- osx