language: go
go:
- 1.10.x
env:
  global:
  - secure: X958L6Vy3Xwn4VzCzfwOPWG5bnuaeVbY2OKXTG2s/KsfeNfrl6/ZkUct5vZL8//+bwJkVVCobVG2KCmUyyeCa1EjR9ED0GH03IUEJlXs1c7v0BacNJ2D2bs8HxsjXHjuDYBh/l1zP6GhGwsZkPhFSx9ViG8M90eg6cUsPlDVppE8PfzhrNa4GwHqGieQTzke7kWiF9484YRcsTLGOgbvkmgCo9uvW/6TFjwkNd6lrjhIcDnB3YPNTP+mDyXBghwpAjTrtV2ZvkbkC4lwM3/gCMww45Y3OUcj8PT1Ez1E86tV/a7EwgyQPo2ho/koe14kyZ0JNZpq5zHaE6L+mJhCqHAITxt2fv81WsCnYnOG5zwtq5N2Re14GIq+wLClTS7/5wYwo1UhtiaBO3Cp5AjetHh8ZnYsNmqmY+7rx1w6/TsdG9i7LCX5rDGdQEOQLpDHRkTx+zEFmlEbPUrEypJ6vEulKkD2ydIzjQmJpRpXpZWA9ItIMcoAcftK5IUlWBuD2rSgHznJdeNVdEcSfiQQXbrKn13ycpK51ENFHp6V6+wJTbNZ4H2qHURDIgkwc2TBMeQ6GpkfsKvdbKZ6FEoZg08ULZathMUxnHaoXc36x4JFqcrcZZsnAxVCUbkDX82mwVIYsGVbM0H8XtHeXrvGCmED1/su3WHfN4S8mWuetTI=
  - secure: KcFIAkrb3+0fuxEcapt4QP+3Eynl1JE8D+z9/7B0d+R+AdZRmr7mUdJqkxw5wqGC/ITlsA6Yyus0KYVPXNTZBmPz7INNPkIXKf24BugOJzCkIO6iUadc9OAxqaz3Q6mD15KB9qW2VwqJbMp/oKAzvwaxVca5PSKpLBrvxDfmCaRmgOwEReIRojnxuQOcDWno+d3M4mW/r8FObrYZKK9hoVBhEHpLi37i+ZWiaB1jKmvyQMX/5uawfZr3507/SEImntYACtmv20GAKIq4+KQoTfYkhIqiK7ObM/5wLlqHiJ+cwt5y0O2WQEJoZDKzVTmxPFFDhhnoAjBmbYYVz9nkAHjQG7IDdv0JS4sroqm35Kldng0mVX9tQWAWj8Xq42+0TVf9XyHbkpYrRykaMvvM2jkpjhMI0FCcw9JmrxTgOOJ8TAA2BCjyXmOAbrEDpX0z87KwfL/cHuShvNMvEBtJNRVleSw8rJPJBEksIOduuhHjLrASI9g48OfwnATivr3P5q3frN/kT4pginmIt5svw4J+jlkpW2MP09z+uD1DYg/gwFIfePRJHlf22tB1EQSFUtQpykVe+TkN0ot+5SpwDX3ol7L5Erft4cnycGHrcAFy5LwQO4ZyW1dAsyQWT3UJBCpnmRAw0RqHWjwKxiM+v8dulwVrU5Aoj1qOSlbO/dw=
os:
  - osx
before_deploy:
  - go get github.com/Songmu/goxz/cmd/goxz
  - go get github.com/tcnksm/ghr
  # See https://github.com/spf13/cobra/issues/250
  - go get github.com/inconshreveable/mousetrap
deploy:
  provider: script
  skip_cleanup: true
  script: chmod +x deploy.sh && sh deploy.sh
  on:
    branch: master
